services:
  _defaults:
    public: true

  # Dummydata configuration form
  expertoprestashop.module.psdummydatagenerator.form.type.dummydata_configuration_text:
    class: 'ExpertoPrestashop\Module\PsDummyDataGenerator\Form\DummydataConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  expertoprestashop.module.psdummydatagenerator.form.dummydata_configuration_form_data_provider:
    class: 'ExpertoPrestashop\Module\PsDummyDataGenerator\Form\DummydataConfigurationFormDataProvider'

  expertoprestashop.module.psdummydatagenerator.form.dummydata_configuration_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@expertoprestashop.module.psdummydatagenerator.form.dummydata_configuration_form_data_provider'
      - 'ExpertoPrestashop\Module\PsDummyDataGenerator\Form\DummydataConfigurationFormType'
      - 'DummydataConfiguration'

  # Entity dummy data generators
  expertoprestashop.module.psdummydatagenerator.generator.category_data_generator:
    class: 'ExpertoPrestashop\Module\PsDummyDataGenerator\Generator\GeneratorCategory'

  expertoprestashop.module.psdummydatagenerator.generator.product_data_generator:
    class: 'ExpertoPrestashop\Module\PsDummyDataGenerator\Generator\GeneratorProduct'

  expertoprestashop.module.psdummydatagenerator.generator.image_data_generator:
    class: 'ExpertoPrestashop\Module\PsDummyDataGenerator\Generator\GeneratorImage'

  expertoprestashop.module.psdummydatagenerator.generator.order_data_generator:
    class: 'ExpertoPrestashop\Module\PsDummyDataGenerator\Generator\GeneratorOrder'
    arguments:
      - '@prestashop.adapter.context_state_manager'
  